### ISSUE TITLE
Multiuser

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/RecipeHandler-4.0#91]
## ToDo
- [x] Jeder Nutzer darf lediglich die von Ihm erstellten Rezepte bearbeiten
- [x] jedes Rezept weist (bspw. über einen Avatar) den Verantwortlichen aus
- [x] Nutzer sollten ihr Passwort über die Oberfläche ändern können
  - zurückgestellt
- [x] ggf. könnte man sich über eine adminPage unterhalten, damit Nutzer aktiviert/deaktiviert werden können
- [x] admin page über den Login Dialog aufrufen lassen
- [x] Verwaltung von theme
- [x] storage rules können nicht auf Daten des firestores zugreifen. Hierfür muss eine eigene Lösung (Cloud Function?!) gebaut werden --> https://stackoverflow.com/a/56606840/12496862
~~**oder** man vertraut auf `request.auth.token.firebase.sign_in_provider != 'anonymous';`~~
- [x] über settings in operator verwenden zur Filterung von selektierten Nutzern
~~attachements aus recipe docs herausziehen --> Jeder Nutzer soll seine eigenen attachements pro Rezept hinterlegen können, jedoch nur seine eigenen löschen~~ **NEUES ISSUE NACH WEIHNACHTEN**
___
## weitere Informationen
- user uids können problemlos öffentlich verfügbar sein - [Quelle](https://stackoverflow.com/questions/37221760/firebase-is-auth-uid-a-shared-secret)
- https://firebase.google.com/docs/firestore/security/rules-conditions#data_validation
